# Generated by Django 5.2.3 on 2025-07-24 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_category_name_alter_participant_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='asset',
            field=models.ImageField(default='event_images/default.jpg', upload_to='event_images'),
        ),
    ]
