# Generated by Django 5.2.3 on 2025-07-25 10:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_asset'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='rsvp_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='asset',
            field=models.ImageField(default='event_images/default.jpg', upload_to='event_images/'),
        ),
        migrations.DeleteModel(
            name='Participant',
        ),
    ]
